Feature:US25 Admin ogrenci olusturama API Testi
  @API
  Scenario: Admin ogrenci olusturuldugunu API ile test edebilir
    Given Student eklemek icin Post request hazirligi yapilir...
    When Admin eklemek icin student request gonderilir...
    Then Student bilgileri dogrulanir
    And student verisi silinir...
    Then silme dogrulama islemi yapilir...